### ISSUE TITLE
Use YAML on templates instead of JSON

### ISSUE THREAD

**Issue by jjmrocha** [jjmrocha/beast#38]
The use of YAML will make the templates for readable and easy to write, example:

```yaml
method: GET
endpoint: "http://domain.io/app/resource/id"
headers:
   - User-Agent: "Beast/1"
request-body: >
   {
      "id": {{ .RequestID }}, 
      "value": "{{ .Data.A }}"
   }
```

Ref:
https://medium.com/@kenanbek/golang-how-to-parse-yaml-file-31b78141bda7
